# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f691974a20e8d285db091eb4096777e8342edfeb0432a759b878bcd8b4afc3fb49da624f75c03161a3db5397cdedf9272993e9fbaf640b7360e5004751c7154

test:
  secret_key_base: 3dded7dd77f5955da3cf84a6a69af0dd1ff97d7529a6ea598e936a2abbada780844ba28529ff69cd9dba6b0a3fc504ee360d72c5e6390b742189e6de1e771236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
